from __future__ import annotations

#editd by mani
CORE_BANKING_GLOSSARY_KNOWLEDGE_BASE = [
    "Business concept: Customer. Canonical ER entity: CUSTOMER. Definition: Individual or organisation holding a banking relationship with the bank. Business usage: Represents the party that owns accounts and is subject to onboarding, servicing, and compliance processes. Notes: Top-level business entity in Core Banking.",
    "Business concept: Customer Contact. Canonical ER entity: CUSTOMER_CONTACT. Definition: Customer communication and address details. Business usage: Stores contactability attributes used for statements, alerts, servicing, and regulatory communication. Notes: Separated from CUSTOMER in normalized design to avoid repeating contact fields.",
    "Business concept: KYC Profile. Canonical ER entity: KYC_PROFILE. Definition: Know Your Customer compliance profile maintained for a customer. Business usage: Tracks KYC completion, risk rating, and review cycle for compliance and regulatory control. Notes: Compliance-focused entity linked to CUSTOMER.",
    "Business concept: Account. Canonical ER entity: ACCOUNT. Definition: Financial record representing customer funds or liabilities. Business usage: Central Core Banking entity through which balances, transactions, fees, and lifecycle events are managed. Notes: Acts as the anchor entity in the Core Banking ER model.",
    "Business concept: Account Balance. Canonical ER entity: ACCOUNT_BALANCE. Definition: Snapshot of account financial position at a point in time. Business usage: Used to represent ledger and available balances for customer channels, finance, and reconciliation. Notes: Often stored as periodic snapshots or intraday balance history.",
    "Business concept: Transaction. Canonical ER entity: TRANSACTION. Definition: Debit or credit movement of funds on an account. Business usage: Represents operational money movement across channels, payments, transfers, withdrawals, and deposits. Notes: High-volume transactional entity.",
    "Business concept: Account Status Event. Canonical ER entity: ACCOUNT_STATUS_EVENT. Definition: Recorded change in operational state of an account. Business usage: Captures events such as open, frozen, dormant, and closed status changes. Notes: Lifecycle tracking entity for accounts.",
    "Business concept: Fee Charge. Canonical ER entity: FEE_CHARGE. Definition: Fee or charge applied to an account. Business usage: Represents service charges such as ATM fee, maintenance fee, penalty fee, or transaction fee. Notes: Operational fee assessment entity.",
    "Business concept: GL Posting. Canonical ER entity: GL_POSTING. Definition: Debit or credit entry posted to the General Ledger. Business usage: Represents accounting impact of transactions and fees into the finance ledger. Notes: Finance-facing accounting entity derived from operational events.",
    "Business concept: GL Account. Canonical ER entity: GL_ACCOUNT. Definition: General Ledger account used for financial classification. Business usage: Represents accounting buckets such as customer deposits, fee income, cash, and suspense accounts. Notes: Reference or master entity used in accounting postings.",
    "Business concept: Normalization. Canonical ER entity: ER Modeling Principle. Definition: Data modeling approach that separates repeating or dependent data into related entities. Business usage: Used in operational and canonical models to reduce redundancy and improve consistency. Notes: In this Core Banking ER, CUSTOMER, CUSTOMER_CONTACT, and KYC_PROFILE are separated in normalized design.",
    "Business concept: De-normalization. Canonical ER entity: Reporting or Analytics View. Definition: Data modeling approach that combines multiple related entities for easier reporting or analytics. Business usage: Commonly used in reporting, analytical marts, and data products. Notes: Useful for CUSTOMER_ACCOUNT_TXN style reporting views.",
    "Business concept: Master Data. Canonical ER entity: CUSTOMER / ACCOUNT / KYC_PROFILE / GL_ACCOUNT. Definition: Relatively stable business data reused across multiple processes. Business usage: Examples include customer, account, KYC profile, and GL account records. Notes: Supports enterprise consistency across domains.",
    "Business concept: Transactional Data. Canonical ER entity: TRANSACTION / ACCOUNT_BALANCE / FEE_CHARGE. Definition: Event-based data that changes frequently and records business activity. Business usage: Examples include transactions, balance snapshots, fee charges, and status events. Notes: Typically high-volume and time-sensitive.",
    "Entity profile: CUSTOMER. Business terms: Customer. Identifiers and reference attributes: customer_id means Unique identifier assigned to a customer. Typical business attributes: first_name means Given name of the customer; last_name means Family name of the customer; customer_type means Segment or type of customer; date_of_birth means Date of birth for an individual customer. Notes and examples: customer_id: Stable business key or surrogate key in enterprise models.; first_name: Synthetic in sample data.; last_name: Synthetic in sample data.; customer_type: Retail / SME / Corporate.; date_of_birth: Needed mainly for retail and compliance use cases.",
    "Entity profile: CUSTOMER_CONTACT. Business terms: Customer Contact. Identifiers and reference attributes: contact_id means Unique identifier for a customer contact record; customer_id means Customer to whom the contact details belong. Typical business attributes: mobile_number means Primary mobile number used for customer communication; email_address means Email address used for alerts and servicing; address_line_1 means Primary street or address line; city means City of residence or correspondence; postal_code means Postal or ZIP code. Notes and examples: customer_id: Links the contact record back to the customer.; mobile_number: Used for alerts and OTP-style contact.; email_address: Used for statements and notifications.",
    "Entity profile: KYC_PROFILE. Business terms: KYC Profile. Identifiers and reference attributes: kyc_profile_id means Unique identifier for the KYC profile; customer_id means Customer to whom the KYC profile belongs. Typical business attributes: kyc_status means Current KYC completion state; risk_rating means Compliance risk rating associated with the customer; review_due_date means Date by which the next KYC review is required. Notes and examples: kyc_status: Pending / Completed / Expired.; risk_rating: Low / Medium / High.",
    "Entity profile: ACCOUNT. Business terms: Account. Identifiers and reference attributes: account_id means Unique identifier for an account; customer_id means Customer who owns the account. Typical business attributes: account_type means Type of banking account; currency means ISO currency in which the account operates; account_status means Current operating status of account. Notes and examples: account_id: Central link to balances and transactions.; customer_id: Links account to customer.; account_type: CASA / TD / OD etc.; currency: GBP / USD / EUR / INR etc.; account_status: Open / Frozen / Dormant / Closed.",
    "Entity profile: ACCOUNT_BALANCE. Business terms: Account Balance. Identifiers and reference attributes: balance_id means Unique identifier for an account balance snapshot; account_id means Account for which the balance was recorded. Typical business attributes: balance_date means Date or timestamp of the balance snapshot; ledger_balance means Official book balance; available_balance means Spendable or withdrawable balance. Notes and examples: available_balance: Important for channel and servicing scenarios.; balance_date: Can be end of day or intraday.",
    "Entity profile: TRANSACTION. Business terms: Transaction. Identifiers and reference attributes: transaction_id means Unique identifier for a transaction; account_id means Account on which the transaction occurred. Typical business attributes: transaction_date means Date and time of the transaction; transaction_type means Classification of transaction; amount means Monetary amount moved; channel means Originating channel for the transaction. Notes and examples: transaction_type: Credit / Debit / Transfer / Withdrawal / Deposit.; channel: Branch / ATM / Mobile / Internet / API.",
    "Entity profile: ACCOUNT_STATUS_EVENT. Business terms: Account Status Event. Identifiers and reference attributes: status_event_id means Unique identifier for an account status event; account_id means Account affected by the status event. Typical business attributes: status_code means New status or status event code; event_timestamp means Time at which the status event occurred; event_reason means Business reason for the status event. Notes and examples: status_code: Opened / Frozen / Dormant / Closed.",
    "Entity profile: FEE_CHARGE. Business terms: Fee Charge. Identifiers and reference attributes: fee_charge_id means Unique identifier for the fee charge; account_id means Account to which the fee was applied. Typical business attributes: fee_type means Category of fee charged; charge_amount means Monetary value of the fee; charge_date means Date on which the fee was applied. Notes and examples: fee_type: ATM Fee / Maintenance Fee / Penalty Fee.",
    "Entity profile: GL_POSTING. Business terms: GL Posting. Identifiers and reference attributes: gl_posting_id means Unique identifier for the general ledger posting; transaction_id means Transaction that triggered the posting; gl_account_id means General ledger account used for the posting. Typical business attributes: posting_date means Date of accounting recognition; debit_credit_indicator means Whether the entry is debit or credit; posting_amount means Monetary amount posted to the ledger. Notes and examples: debit_credit_indicator: D or C.",
    "Entity profile: GL_ACCOUNT. Business terms: GL Account. Identifiers and reference attributes: gl_account_id means Unique identifier for a general ledger account. Typical business attributes: gl_account_code means Accounting classification code; gl_account_name means Human-readable ledger name; gl_account_type means Type of ledger account. Notes and examples: gl_account_type: Asset / Liability / Income / Expense.",
]
